### PR TITLE
Wazo 2904 wazo confgend convert one generator to stevedore plugin

### PR DESCRIPTION
**Pull request by DrPyser**
https://wazo-dev.atlassian.net/browse/WAZO-2904

As a first contribution and in an effort to simplify modular handling of configurations, the support for asterisk/features.conf has been converted to the plugin interface.

As a continuation in this direction, all remaining configuration generators implemented through/behind "frontend" abstractions(`asterisk.AsteriskFrontend`, `wazo.WazoFrontend`, `phoned.PhonedFrontend`) should be converted to the plugin-based architecture. 
That is, all supported configurations can be declared as an entrypoint in the setup.py, and all implementations of configuration generators can follow the same interface: a class with a `generate` method taking no argument and returning a string containing the complete configuration. 
This should then enable use to remove the "frontend" layer and the `wazo_confgend.generators.*` non-utility modules in order to simplify the codebase.

Included commits were tested manually on an aws test environment wazo stack. 
After verifying through logs that the plugin was properly loaded and called from an invocation of `wazo-confgen asterisk/features.conf`, `diff` was invoked with the new output and a previously generated `features.conf`from the current production version, which verified the equivalence(no difference).

### CODE REVIEW

**Comment by DrPyser** [comment]
recheck

**Comment by sduthil** [comment]
recheck

**Comment by DrPyser** [comment]
recheck

**Review by pc-m — APPROVED** [review]

**Comment by fblackburn1** [comment]
> 3\. Make the logger global to the module. Not that its better but its the way other loggers are instantiated.

@DrPyser any reason to do not resolve this comment?

**Pull request merged**
