### PR TITLE
WAZO-1913 - Pjsip

### PR DESCRIPTION
**Pull request by fblackburn1**
Depends-on: https://github.com/wazo-platform/sf-jobs/pull/58
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/67

### CODE REVIEW

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Review by pc-m — APPROVED** [review]

**Pull request merged**
