### PR TITLE
add a generator for asterisk/modules.conf

### PR DESCRIPTION
**Pull request by pc-m**

### CODE REVIEW

**Comment by pc-m** [comment]
> I do not understand why we need of confgend to generate modules.conf?

I would have expected the opposite question if I did not add it to confgend...
`Why didn't you add it to confgend like ALL other Asterisk configuration generators?`

**Comment by pc-m** [comment]
The Asterisk module which contains the mechanism that loads configuration and execute `;exec` is not loaded since its the `modules.conf`.

asterisk.conf and modules.conf are "special" like that

**Comment by fblackburn1** [comment]
> > I do not understand why we need of confgend to generate modules.conf?
> 
> I would have expected the opposite question if I did not add it to confgend...
> `Why didn't you add it to confgend like ALL other Asterisk configuration generators?`

Because the job of wazo-confgend is to interface database to generate config files for those who need it. Not specially for asterisk files.
I think this usecase is weird and not the responsibility of wazo-confgend.
wazo-confgend should be totally transparency for the admin, so it's weird to setting asterisk config inside confgend.:confused:
To follow what we have already done, the modules.conf should be configured by an API REST through wazo-confd. I don't like this *half* step since the api implement is straightforward

**Comment by fblackburn1** [comment]
Understand me well, I'm not against this method (or the merge), I just don't like it.
We should to minumum open a ticket (feature) to indicate in which way we want for this configuration if we agree

**Comment by pc-m** [comment]
I've created a ticket for the generation of `/etc/asterisk/modules.conf`
https://wazo-dev.atlassian.net/browse/WAZO-1359

**Pull request merged**
